import oracledb
import config

def init():
    print("Connecting to Oracle 19c...")
    conn = oracledb.connect(
        user=config.DB_USER,
        password=config.DB_PASSWORD,
        dsn=config.DSN
    )
    cursor = conn.cursor()
    print("Connected successfully! Oracle Version:", conn.version)

    # 1. Clean up tables
    tables = ['ALERTS', 'PREDICTIONS', 'RECURRINGPAYMENTS', 'BUDGETS', 'TRANSACTIONS', 'CATEGORIES', 'ACCOUNTS', 'USERS']
    for t in tables:
        try:
            cursor.execute(f"DROP TABLE {t} CASCADE CONSTRAINTS")
            print(f"Dropped table {t}")
        except oracledb.DatabaseError as e:
            pass # Table didn't exist

    print("Tables dropped (if existed).")

    # 2. Create Users
    cursor.execute("""
    CREATE TABLE Users (
        user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name          VARCHAR2(100) NOT NULL,
        email         VARCHAR2(150) NOT NULL UNIQUE,
        password_hash VARCHAR2(255) NOT NULL,
        role          VARCHAR2(20) DEFAULT 'USER' NOT NULL,
        created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT chk_user_role CHECK (role IN ('ADMIN', 'USER'))
    )
    """)
    print("Created Users table")

    # 3. Create Accounts
    cursor.execute("""
    CREATE TABLE Accounts (
        account_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id      NUMBER NOT NULL,
        account_type VARCHAR2(30) NOT NULL,
        balance      NUMBER(12,2) DEFAULT 0.00 NOT NULL,
        status       VARCHAR2(20) DEFAULT 'Active' NOT NULL,
        opened_at    DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT fk_acc_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
        CONSTRAINT chk_acc_type CHECK (account_type IN ('Savings', 'Current', 'Credit', 'Wallet')),
        CONSTRAINT chk_acc_status CHECK (status IN ('Active', 'Frozen'))
    )
    """)
    print("Created Accounts table")

    # 4. Create Categories
    cursor.execute("""
    CREATE TABLE Categories (
        category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_name VARCHAR2(60) NOT NULL UNIQUE,
        type          VARCHAR2(10) NOT NULL,
        CONSTRAINT chk_cat_type CHECK (type IN ('Income', 'Expense'))
    )
    """)
    print("Created Categories table")

    # 5. Create Transactions
    cursor.execute("""
    CREATE TABLE Transactions (
        transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_id     NUMBER NOT NULL,
        category_id    NUMBER NOT NULL,
        amount         NUMBER(12,2) NOT NULL,
        txn_type       VARCHAR2(10) NOT NULL,
        txn_date       DATE DEFAULT SYSDATE NOT NULL,
        vendor         VARCHAR2(100),
        description    VARCHAR2(255),
        CONSTRAINT fk_txn_account FOREIGN KEY (account_id) REFERENCES Accounts(account_id) ON DELETE CASCADE,
        CONSTRAINT fk_txn_category FOREIGN KEY (category_id) REFERENCES Categories(category_id),
        CONSTRAINT chk_txn_amount CHECK (amount > 0),
        CONSTRAINT chk_txn_type CHECK (txn_type IN ('Credit', 'Debit'))
    )
    """)
    print("Created Transactions table")

    # 6. Create Budgets
    cursor.execute("""
    CREATE TABLE Budgets (
        budget_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id      NUMBER NOT NULL,
        category_id  NUMBER NOT NULL,
        month        VARCHAR2(7) NOT NULL,
        limit_amount NUMBER(12,2) NOT NULL,
        CONSTRAINT fk_budget_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
        CONSTRAINT fk_budget_category FOREIGN KEY (category_id) REFERENCES Categories(category_id),
        CONSTRAINT chk_budget_limit CHECK (limit_amount > 0),
        CONSTRAINT uq_budget_user_cat_month UNIQUE (user_id, category_id, month)
    )
    """)
    print("Created Budgets table")

    # 7. Create RecurringPayments
    cursor.execute("""
    CREATE TABLE RecurringPayments (
        recurring_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_id    NUMBER NOT NULL,
        category_id   NUMBER NOT NULL,
        amount        NUMBER(12,2) NOT NULL,
        frequency     VARCHAR2(10) NOT NULL,
        next_due_date DATE NOT NULL,
        CONSTRAINT fk_rec_account FOREIGN KEY (account_id) REFERENCES Accounts(account_id) ON DELETE CASCADE,
        CONSTRAINT fk_rec_category FOREIGN KEY (category_id) REFERENCES Categories(category_id),
        CONSTRAINT chk_rec_amount CHECK (amount > 0),
        CONSTRAINT chk_rec_freq CHECK (frequency IN ('Weekly', 'Monthly', 'Yearly'))
    )
    """)
    print("Created RecurringPayments table")

    # 8. Create Predictions
    cursor.execute("""
    CREATE TABLE Predictions (
        prediction_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id          NUMBER NOT NULL,
        category_id      NUMBER NOT NULL,
        month            VARCHAR2(7) NOT NULL,
        predicted_amount NUMBER(12,2) NOT NULL,
        method           VARCHAR2(30) DEFAULT 'moving_avg' NOT NULL,
        CONSTRAINT fk_pred_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
        CONSTRAINT fk_pred_category FOREIGN KEY (category_id) REFERENCES Categories(category_id),
        CONSTRAINT uq_pred_user_cat_month UNIQUE (user_id, category_id, month)
    )
    """)
    print("Created Predictions table")

    # 9. Create Alerts
    cursor.execute("""
    CREATE TABLE Alerts (
        alert_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id    NUMBER NOT NULL,
        message    VARCHAR2(400) NOT NULL,
        alert_type VARCHAR2(30) DEFAULT 'WARNING' NOT NULL,
        is_read    NUMBER(1) DEFAULT 0 NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT fk_alert_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
    )
    """)
    print("Created Alerts table")

    # 10. Create Performance Indexes
    print("Creating performance indexes...")
    indexes = [
        "CREATE INDEX idx_txn_acc_date ON Transactions(account_id, txn_date)",
        "CREATE INDEX idx_txn_cat ON Transactions(category_id)",
        "CREATE INDEX idx_txn_vendor ON Transactions(vendor)",
        "CREATE INDEX idx_budget_user_month ON Budgets(user_id, month)",
        "CREATE INDEX idx_recurring_due ON RecurringPayments(next_due_date)"
    ]
    for idx_sql in indexes:
        try:
            cursor.execute(idx_sql)
        except Exception:
            pass
    print("Created performance indexes")

    # 10. Create Views
    print("Creating views...")
    cursor.execute("""
    CREATE OR REPLACE VIEW v_monthly_category_summary AS
    SELECT 
        a.user_id,
        c.category_id,
        c.category_name,
        c.type AS category_type,
        TO_CHAR(t.txn_date, 'YYYY-MM') AS month,
        SUM(t.amount) AS total_amount,
        COUNT(t.transaction_id) AS txn_count
    FROM Transactions t
    JOIN Accounts a ON t.account_id = a.account_id
    JOIN Categories c ON t.category_id = c.category_id
    GROUP BY 
        a.user_id, 
        c.category_id, 
        c.category_name, 
        c.type, 
        TO_CHAR(t.txn_date, 'YYYY-MM')
    """)
    print("Created view: v_monthly_category_summary")

    cursor.execute("""
    CREATE OR REPLACE VIEW v_budget_vs_actual AS
    SELECT 
        b.budget_id,
        b.user_id,
        b.category_id,
        c.category_name,
        b.month,
        b.limit_amount,
        NVL(actual.total_spent, 0) AS actual_spent,
        (b.limit_amount - NVL(actual.total_spent, 0)) AS remaining_amount,
        CASE 
            WHEN NVL(actual.total_spent, 0) > b.limit_amount THEN 'EXCEEDED'
            WHEN NVL(actual.total_spent, 0) >= (0.85 * b.limit_amount) THEN 'WARNING'
            ELSE 'ON_TRACK'
        END AS status,
        ROUND(CASE 
            WHEN b.limit_amount > 0 THEN (NVL(actual.total_spent, 0) / b.limit_amount) * 100 
            ELSE 0 
        END, 2) AS percent_used
    FROM Budgets b
    JOIN Categories c ON b.category_id = c.category_id
    LEFT JOIN (
        SELECT 
            a.user_id,
            t.category_id,
            TO_CHAR(t.txn_date, 'YYYY-MM') AS month,
            SUM(t.amount) AS total_spent
        FROM Transactions t
        JOIN Accounts a ON t.account_id = a.account_id
        WHERE t.txn_type = 'Debit'
        GROUP BY a.user_id, t.category_id, TO_CHAR(t.txn_date, 'YYYY-MM')
    ) actual ON b.user_id = actual.user_id 
            AND b.category_id = actual.category_id 
            AND b.month = actual.month
    """)
    print("Created view: v_budget_vs_actual")

    # 11. Create Triggers
    print("Creating triggers...")
    cursor.execute("""
    CREATE OR REPLACE TRIGGER trg_update_account_balance
    AFTER INSERT OR DELETE ON Transactions
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            IF :NEW.txn_type = 'Credit' THEN
                UPDATE Accounts 
                SET balance = balance + :NEW.amount 
                WHERE account_id = :NEW.account_id;
            ELSIF :NEW.txn_type = 'Debit' THEN
                UPDATE Accounts 
                SET balance = balance - :NEW.amount 
                WHERE account_id = :NEW.account_id;
            END IF;
        ELSIF DELETING THEN
            IF :OLD.txn_type = 'Credit' THEN
                UPDATE Accounts 
                SET balance = balance - :OLD.amount 
                WHERE account_id = :OLD.account_id;
            ELSIF :OLD.txn_type = 'Debit' THEN
                UPDATE Accounts 
                SET balance = balance + :OLD.amount 
                WHERE account_id = :OLD.account_id;
            END IF;
        END IF;
    END;
    """)
    print("Created trigger: trg_update_account_balance")

    cursor.execute("""
    CREATE OR REPLACE TRIGGER trg_check_budget_overrun
    FOR INSERT ON Transactions
    COMPOUND TRIGGER

        TYPE t_txn_record IS RECORD (
            account_id   Transactions.account_id%TYPE,
            category_id  Transactions.category_id%TYPE,
            txn_date     Transactions.txn_date%TYPE,
            txn_type     Transactions.txn_type%TYPE
        );
        TYPE t_txn_list IS TABLE OF t_txn_record INDEX BY PLS_INTEGER;
        g_txns t_txn_list;
        g_count PLS_INTEGER := 0;

        AFTER EACH ROW IS
        BEGIN
            IF :NEW.txn_type = 'Debit' THEN
                g_count := g_count + 1;
                g_txns(g_count).account_id := :NEW.account_id;
                g_txns(g_count).category_id := :NEW.category_id;
                g_txns(g_count).txn_date := :NEW.txn_date;
                g_txns(g_count).txn_type := :NEW.txn_type;
            END IF;
        END AFTER EACH ROW;

        AFTER STATEMENT IS
            v_user_id      NUMBER;
            v_month        VARCHAR2(7);
            v_total_spent  NUMBER(12,2);
            v_limit        NUMBER(12,2);
            v_cat_name     VARCHAR2(60);
            v_alert_exists NUMBER;
        BEGIN
            FOR i IN 1..g_count LOOP
                BEGIN
                    SELECT user_id INTO v_user_id
                    FROM Accounts WHERE account_id = g_txns(i).account_id;
                EXCEPTION
                    WHEN NO_DATA_FOUND THEN CONTINUE;
                END;

                v_month := TO_CHAR(g_txns(i).txn_date, 'YYYY-MM');

                BEGIN
                    SELECT b.limit_amount, c.category_name
                    INTO v_limit, v_cat_name
                    FROM Budgets b
                    JOIN Categories c ON b.category_id = c.category_id
                    WHERE b.user_id = v_user_id
                      AND b.category_id = g_txns(i).category_id
                      AND b.month = v_month;
                EXCEPTION
                    WHEN NO_DATA_FOUND THEN
                        CONTINUE;
                END;

                SELECT NVL(SUM(t.amount), 0)
                INTO v_total_spent
                FROM Transactions t
                JOIN Accounts a ON t.account_id = a.account_id
                WHERE a.user_id = v_user_id
                  AND t.category_id = g_txns(i).category_id
                  AND t.txn_type = 'Debit'
                  AND TO_CHAR(t.txn_date, 'YYYY-MM') = v_month;

                IF v_total_spent > v_limit THEN
                    SELECT COUNT(*) INTO v_alert_exists
                    FROM Alerts
                    WHERE user_id = v_user_id
                      AND message LIKE '%' || v_cat_name || '%' || v_month || '%'
                      AND TRUNC(created_at) = TRUNC(SYSDATE);

                    IF v_alert_exists = 0 THEN
                        INSERT INTO Alerts (user_id, message, alert_type, is_read, created_at)
                        VALUES (
                            v_user_id,
                            'Budget Overrun: Category "' || v_cat_name || '" reached ' || 
                            TO_CHAR(v_total_spent, 'FM999,990.00') || ' exceeding limit of ' || 
                            TO_CHAR(v_limit, 'FM999,990.00') || ' for ' || v_month || '.',
                            'BUDGET_OVERRUN',
                            0,
                            SYSDATE
                        );
                    END IF;
                END IF;
            END LOOP;

            g_count := 0;
            g_txns.DELETE;
        END AFTER STATEMENT;

    END trg_check_budget_overrun;
    """)
    print("Created trigger: trg_check_budget_overrun")

    # 12. Create Functions and Procedures
    print("Creating functions & procedures...")
    cursor.execute("""
    CREATE OR REPLACE FUNCTION get_monthly_total (
        p_user_id IN NUMBER,
        p_month   IN VARCHAR2
    ) RETURN NUMBER
    IS
        v_total NUMBER(12,2) := 0;
    BEGIN
        SELECT NVL(SUM(t.amount), 0)
        INTO v_total
        FROM Transactions t
        JOIN Accounts a ON t.account_id = a.account_id
        WHERE a.user_id = p_user_id
          AND t.txn_type = 'Debit'
          AND TO_CHAR(t.txn_date, 'YYYY-MM') = p_month;

        RETURN v_total;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 0;
    END;
    """)
    print("Created function: get_monthly_total")

    cursor.execute("""
    CREATE OR REPLACE PROCEDURE transfer_funds (
        p_from_account IN NUMBER,
        p_to_account   IN NUMBER,
        p_amount       IN NUMBER,
        p_description  IN VARCHAR2,
        p_out_status   OUT VARCHAR2
    )
    IS
        v_from_balance NUMBER(12,2);
        v_cat_id       NUMBER;
        v_from_user    NUMBER;
        v_to_user      NUMBER;
    BEGIN
        IF p_amount <= 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Transfer amount must be greater than zero.');
        END IF;

        IF p_from_account = p_to_account THEN
            RAISE_APPLICATION_ERROR(-20002, 'Source and destination accounts must be different.');
        END IF;

        BEGIN
            SELECT balance, user_id INTO v_from_balance, v_from_user
            FROM Accounts
            WHERE account_id = p_from_account
            FOR UPDATE;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20003, 'Source account does not exist.');
        END;

        BEGIN
            SELECT user_id INTO v_to_user
            FROM Accounts
            WHERE account_id = p_to_account;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20004, 'Destination account does not exist.');
        END;

        IF v_from_balance < p_amount THEN
            RAISE_APPLICATION_ERROR(-20005, 'Insufficient balance in source account. Current balance: ' || v_from_balance);
        END IF;

        BEGIN
            SELECT category_id INTO v_cat_id 
            FROM Categories 
            WHERE category_name = 'Transfer' AND ROWNUM = 1;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO Categories (category_name, type) 
                VALUES ('Transfer', 'Expense')
                RETURNING category_id INTO v_cat_id;
        END;

        INSERT INTO Transactions (account_id, category_id, amount, txn_type, txn_date, description)
        VALUES (
            p_from_account, 
            v_cat_id, 
            p_amount, 
            'Debit', 
            SYSDATE, 
            NVL(p_description, 'Fund Transfer to Acc #' || p_to_account)
        );

        INSERT INTO Transactions (account_id, category_id, amount, txn_type, txn_date, description)
        VALUES (
            p_to_account, 
            v_cat_id, 
            p_amount, 
            'Credit', 
            SYSDATE, 
            NVL(p_description, 'Fund Transfer from Acc #' || p_from_account)
        );

        COMMIT;
        p_out_status := 'SUCCESS: Transferred ' || TO_CHAR(p_amount, 'FM999,999,990.00') || ' successfully.';

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_out_status := 'FAILED: ' || SQLERRM;
            RAISE;
    END;
    """)
    print("Created procedure: transfer_funds")

    cursor.execute("""
    CREATE OR REPLACE PROCEDURE generate_recurring_transactions (
        p_out_count OUT NUMBER
    )
    IS
        CURSOR cur_recurring IS
            SELECT recurring_id, account_id, category_id, amount, frequency, next_due_date
            FROM RecurringPayments
            WHERE TRUNC(next_due_date) <= TRUNC(SYSDATE)
            FOR UPDATE;

        v_count NUMBER := 0;
        v_next_date DATE;
        v_cat_name VARCHAR2(60);
    BEGIN
        FOR rec IN cur_recurring LOOP
            SELECT category_name INTO v_cat_name
            FROM Categories WHERE category_id = rec.category_id;

            INSERT INTO Transactions (account_id, category_id, amount, txn_type, txn_date, description)
            VALUES (
                rec.account_id,
                rec.category_id,
                rec.amount,
                'Debit',
                SYSDATE,
                'Auto-Recurring: ' || v_cat_name || ' (' || rec.frequency || ')'
            );

            IF UPPER(rec.frequency) = 'WEEKLY' THEN
                v_next_date := rec.next_due_date + 7;
            ELSIF UPPER(rec.frequency) = 'YEARLY' THEN
                v_next_date := ADD_MONTHS(rec.next_due_date, 12);
            ELSE
                v_next_date := ADD_MONTHS(rec.next_due_date, 1);
            END IF;

            UPDATE RecurringPayments
            SET next_due_date = v_next_date
            WHERE CURRENT OF cur_recurring;

            v_count := v_count + 1;
        END LOOP;

        COMMIT;
        p_out_count := v_count;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_out_count := 0;
            RAISE;
    END;
    """)
    print("Created procedure: generate_recurring_transactions")

    cursor.execute("""
    CREATE OR REPLACE PROCEDURE generate_monthly_predictions (
        p_user_id      IN NUMBER,
        p_target_month IN VARCHAR2,
        p_out_count    OUT NUMBER
    )
    IS
        v_count NUMBER := 0;
    BEGIN
        MERGE INTO Predictions p
        USING (
            WITH MonthlySpend AS (
                SELECT 
                    a.user_id,
                    t.category_id,
                    TO_CHAR(t.txn_date, 'YYYY-MM') AS month_str,
                    SUM(t.amount) AS monthly_sum
                FROM Transactions t
                JOIN Accounts a ON t.account_id = a.account_id
                WHERE a.user_id = p_user_id
                  AND t.txn_type = 'Debit'
                GROUP BY a.user_id, t.category_id, TO_CHAR(t.txn_date, 'YYYY-MM')
            ),
            MovingAverages AS (
                SELECT 
                    user_id,
                    category_id,
                    month_str,
                    ROUND(AVG(monthly_sum) OVER (
                        PARTITION BY user_id, category_id 
                        ORDER BY month_str 
                        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
                    ), 2) AS moving_avg_spend,
                    ROW_NUMBER() OVER (
                        PARTITION BY user_id, category_id 
                        ORDER BY month_str DESC
                    ) AS rn
                FROM MonthlySpend
            )
            SELECT 
                user_id,
                category_id,
                p_target_month AS month,
                moving_avg_spend AS predicted_amount,
                'moving_avg_3m' AS method
            FROM MovingAverages
            WHERE rn = 1
        ) src
        ON (p.user_id = src.user_id AND p.category_id = src.category_id AND p.month = src.month)
        WHEN MATCHED THEN
            UPDATE SET 
                p.predicted_amount = src.predicted_amount,
                p.method = src.method
        WHEN NOT MATCHED THEN
            INSERT (user_id, category_id, month, predicted_amount, method)
            VALUES (src.user_id, src.category_id, src.month, src.predicted_amount, src.method);

        v_count := SQL%ROWCOUNT;
        COMMIT;
        p_out_count := v_count;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_out_count := 0;
            RAISE;
    END;
    """)
    print("Created procedure: generate_monthly_predictions")

    # 13. Populate Seed Data
    print("Populating seed data...")
    categories = [
        ('Salary', 'Income'), ('Freelancing', 'Income'), ('Investments', 'Income'),
        ('Groceries', 'Expense'), ('Food & Dining', 'Expense'), ('Rent & Housing', 'Expense'),
        ('Utilities', 'Expense'), ('Transportation', 'Expense'), ('Entertainment', 'Expense'),
        ('Healthcare', 'Expense'), ('Subscriptions', 'Expense'), ('Shopping', 'Expense'),
        ('Transfer', 'Expense')
    ]
    cursor.executemany("INSERT INTO Categories (category_name, type) VALUES (:1, :2)", categories)

    users = [
        ('Harshith K', 'harshith@example.com', '$2b$12$5KyFFZYZtfTSq45nbEpin.Y0tiLRf6xB/4VUNzyKI4kssKXeSQIoK', 'USER'),
        ('Manideep P', 'manideep@example.com', '$2b$12$5KyFFZYZtfTSq45nbEpin.Y0tiLRf6xB/4VUNzyKI4kssKXeSQIoK', 'USER'),
        ('Rishvik K', 'rishvik@example.com', '$2b$12$5KyFFZYZtfTSq45nbEpin.Y0tiLRf6xB/4VUNzyKI4kssKXeSQIoK', 'USER'),
        ('System Administrator', 'admin@fintrack.com', '$2b$12$ZuJLjWbBvnJWsntSXKXJy.c6UK6GRPe0ZlEm60VaBTpUxYmDDyQBy', 'ADMIN')
    ]
    cursor.executemany("INSERT INTO Users (name, email, password_hash, role) VALUES (:1, :2, :3, :4)", users)

    # Accounts
    cursor.execute("INSERT INTO Accounts (user_id, account_type, balance, opened_at) VALUES (1, 'Savings', 0.00, DATE '2026-06-01')")
    cursor.execute("INSERT INTO Accounts (user_id, account_type, balance, opened_at) VALUES (1, 'Current', 0.00, DATE '2026-06-01')")
    cursor.execute("INSERT INTO Accounts (user_id, account_type, balance, opened_at) VALUES (1, 'Wallet', 0.00, DATE '2026-06-01')")
    cursor.execute("INSERT INTO Accounts (user_id, account_type, balance, opened_at) VALUES (2, 'Savings', 0.00, DATE '2026-06-01')")

    # Transactions (which trigger balance updates)
    txns = [
        # Credits
        (1, 1, 75000.00, 'Credit', "DATE '2026-07-01'", 'Monthly Salary July'),
        (1, 1, 75000.00, 'Credit', "DATE '2026-08-01'", 'Monthly Salary August'),
        (1, 1, 75000.00, 'Credit', "DATE '2026-09-01'", 'Monthly Salary September'),
        (1, 1, 75000.00, 'Credit', "DATE '2026-10-01'", 'Monthly Salary October'),
        (2, 2, 25000.00, 'Credit', "DATE '2026-09-15'", 'Freelance Project Payout'),
        (3, 1, 5000.00, 'Credit', "DATE '2026-10-01'", 'Wallet Top-up from Bank'),

        # July 2026 Expenses
        (1, 6, 20000.00, 'Debit', "DATE '2026-07-02'", 'Apartment Rent July'),
        (1, 4, 6200.00, 'Debit', "DATE '2026-07-05'", 'Monthly Supermarket Groceries'),
        (1, 5, 3100.00, 'Debit', "DATE '2026-07-12'", 'Weekend Dining & Outing'),
        (1, 7, 2400.00, 'Debit', "DATE '2026-07-15'", 'Electricity & Water Bill'),
        (1, 8, 1800.00, 'Debit', "DATE '2026-07-20'", 'Fuel & Metro card refill'),
        (1, 9, 1500.00, 'Debit', "DATE '2026-07-25'", 'Movie tickets and bowling'),

        # August 2026 Expenses
        (1, 6, 20000.00, 'Debit', "DATE '2026-08-02'", 'Apartment Rent August'),
        (1, 4, 6800.00, 'Debit', "DATE '2026-08-06'", 'Supermarket & Organic Mart'),
        (1, 5, 3900.00, 'Debit', "DATE '2026-08-14'", 'Family Restaurant Dinner'),
        (1, 7, 2600.00, 'Debit', "DATE '2026-08-16'", 'Electricity & Gas Utility'),
        (1, 8, 2100.00, 'Debit', "DATE '2026-08-22'", 'Cab & Petrol'),
        (1, 9, 2000.00, 'Debit', "DATE '2026-08-28'", 'Music Concert entry'),

        # September 2026 Expenses
        (1, 6, 20000.00, 'Debit', "DATE '2026-09-02'", 'Apartment Rent September'),
        (1, 4, 7100.00, 'Debit', "DATE '2026-09-07'", 'Wholesale Grocery Supplies'),
        (1, 5, 4200.00, 'Debit', "DATE '2026-09-18'", 'Dinner & Cafe Coffee'),
        (1, 7, 2800.00, 'Debit', "DATE '2026-09-19'", 'Power Grid Utility Bill'),
        (1, 8, 1950.00, 'Debit', "DATE '2026-09-24'", 'Metro Pass & Uber'),
        (1, 9, 1800.00, 'Debit', "DATE '2026-09-29'", 'Gaming & Arcade'),

        # October 2026 Initial Expenses
        (1, 6, 20000.00, 'Debit', "DATE '2026-10-01'", 'Apartment Rent October'),
        (1, 4, 3200.00, 'Debit', "DATE '2026-10-01'", 'Weekly Groceries')
    ]
    for acc_id, cat_id, amt, ttype, dt, desc in txns:
        cursor.execute(f"""
            INSERT INTO Transactions (account_id, category_id, amount, txn_type, txn_date, description)
            VALUES ({acc_id}, {cat_id}, {amt}, '{ttype}', {dt}, '{desc}')
        """)

    # Budgets for October 2026
    budgets = [
        (1, 4, '2026-10', 8000.00),
        (1, 5, '2026-10', 4000.00),
        (1, 6, '2026-10', 21000.00),
        (1, 7, '2026-10', 3000.00),
        (1, 8, '2026-10', 2500.00),
        (1, 9, '2026-10', 2000.00)
    ]
    cursor.executemany("INSERT INTO Budgets (user_id, category_id, month, limit_amount) VALUES (:1, :2, :3, :4)", budgets)

    # Recurring Payments
    cursor.execute("INSERT INTO RecurringPayments (account_id, category_id, amount, frequency, next_due_date) VALUES (1, 11, 499.00, 'Monthly', TRUNC(SYSDATE))")
    cursor.execute("INSERT INTO RecurringPayments (account_id, category_id, amount, frequency, next_due_date) VALUES (1, 11, 199.00, 'Monthly', TRUNC(SYSDATE) + 5)")
    cursor.execute("INSERT INTO RecurringPayments (account_id, category_id, amount, frequency, next_due_date) VALUES (1, 7, 999.00, 'Monthly', TRUNC(SYSDATE) + 10)")
    cursor.execute("INSERT INTO RecurringPayments (account_id, category_id, amount, frequency, next_due_date) VALUES (1, 6, 20000.00, 'Monthly', ADD_MONTHS(TRUNC(SYSDATE), 1))")

    conn.commit()
    print("Seed data successfully inserted and committed!")

    # Verify Account balances updated by trigger
    cursor.execute("SELECT account_id, account_type, balance FROM Accounts ORDER BY account_id")
    rows = cursor.fetchall()
    print("\nVerified Account Balances (updated automatically via trigger):")
    for r in rows:
        print(f"  Account #{r[0]} ({r[1]}): Rs. {r[2]:,.2f}")

    cursor.close()
    conn.close()
    print("\nDatabase initialization and verification completed 100% successfully!")

if __name__ == '__main__':
    init()
