-- ====================================================================
-- Project: Personal Finance Management with Spending Prediction
-- Authors: K. Harshith, P. Manideep, K. Rishvik
-- DBMS: Oracle Database 19c
-- File: 01_schema.sql
-- Description: DDL script creating all 7 normalized relational tables
-- ====================================================================

-- Clean up existing objects if any
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN 
              ('ALERTS', 'PREDICTIONS', 'RECURRINGPAYMENTS', 'BUDGETS', 'TRANSACTIONS', 'CATEGORIES', 'ACCOUNTS', 'USERS')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- 1. USERS
-- Base entity for authentication and ownership
CREATE TABLE Users (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL,
    email         VARCHAR2(150) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role          VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_user_role CHECK (role IN ('ADMIN', 'USER'))
);

-- 2. ACCOUNTS
-- One user can hold multiple accounts (Savings, Current, Credit, Wallet)
CREATE TABLE Accounts (
    account_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER NOT NULL,
    account_type VARCHAR2(30) NOT NULL,
    balance      NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    status       VARCHAR2(20) DEFAULT 'Active' NOT NULL,
    opened_at    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_acc_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_acc_type CHECK (account_type IN ('Savings', 'Current', 'Credit', 'Wallet')),
    CONSTRAINT chk_acc_status CHECK (status IN ('Active', 'Frozen'))
);

-- 3. CATEGORIES
-- Lookup table for income/expense classifications
CREATE TABLE Categories (
    category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(60) NOT NULL UNIQUE,
    type          VARCHAR2(10) NOT NULL,
    CONSTRAINT chk_cat_type CHECK (type IN ('Income', 'Expense'))
);

-- 4. TRANSACTIONS
-- Central fact table logging all credits and debits
CREATE TABLE Transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     NUMBER NOT NULL,
    category_id    NUMBER NOT NULL,
    amount         NUMBER(12,2) NOT NULL,
    txn_type       VARCHAR2(10) NOT NULL,
    txn_date       DATE DEFAULT SYSDATE NOT NULL,
    vendor         VARCHAR2(100),
    description    VARCHAR2(255),
    CONSTRAINT fk_txn_account FOREIGN KEY (account_id) REFERENCES Accounts(account_id) ON DELETE CASCADE,
    CONSTRAINT fk_txn_category FOREIGN KEY (category_id) REFERENCES Categories(category_id),
    CONSTRAINT chk_txn_amount CHECK (amount > 0),
    CONSTRAINT chk_txn_type CHECK (txn_type IN ('Credit', 'Debit'))
);

-- 5. BUDGETS
-- Monthly budget limits per user and category
CREATE TABLE Budgets (
    budget_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER NOT NULL,
    category_id  NUMBER NOT NULL,
    month        VARCHAR2(7) NOT NULL, -- Format: YYYY-MM
    limit_amount NUMBER(12,2) NOT NULL,
    CONSTRAINT fk_budget_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_budget_category FOREIGN KEY (category_id) REFERENCES Categories(category_id),
    CONSTRAINT chk_budget_limit CHECK (limit_amount > 0),
    CONSTRAINT uq_budget_user_cat_month UNIQUE (user_id, category_id, month)
);

-- 6. RECURRING PAYMENTS
-- Auto-scheduled transactions (subscriptions, EMIs, salaries)
CREATE TABLE RecurringPayments (
    recurring_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    NUMBER NOT NULL,
    category_id   NUMBER NOT NULL,
    amount        NUMBER(12,2) NOT NULL,
    frequency     VARCHAR2(10) NOT NULL,
    next_due_date DATE NOT NULL,
    CONSTRAINT fk_rec_account FOREIGN KEY (account_id) REFERENCES Accounts(account_id) ON DELETE CASCADE,
    CONSTRAINT fk_rec_category FOREIGN KEY (category_id) REFERENCES Categories(category_id),
    CONSTRAINT chk_rec_amount CHECK (amount > 0),
    CONSTRAINT chk_rec_freq CHECK (frequency IN ('Weekly', 'Monthly', 'Yearly'))
);

-- 7. PREDICTIONS
-- Stores forecasting results generated via Window Functions / Moving Average
CREATE TABLE Predictions (
    prediction_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL,
    category_id      NUMBER NOT NULL,
    month            VARCHAR2(7) NOT NULL, -- Format: YYYY-MM
    predicted_amount NUMBER(12,2) NOT NULL,
    method           VARCHAR2(30) DEFAULT 'moving_avg' NOT NULL,
    CONSTRAINT fk_pred_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_pred_category FOREIGN KEY (category_id) REFERENCES Categories(category_id),
    CONSTRAINT uq_pred_user_cat_month UNIQUE (user_id, category_id, month)
);

-- 8. ALERTS
-- Supporting table for trigger-driven budget overrun notifications
CREATE TABLE Alerts (
    alert_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    NUMBER NOT NULL,
    message    VARCHAR2(400) NOT NULL,
    alert_type VARCHAR2(30) DEFAULT 'WARNING' NOT NULL,
    is_read    NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_alert_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- ====================================================================
-- Performance Indexes (Optimizing Filter & Ledger Lookups)
-- ====================================================================
CREATE INDEX idx_txn_acc_date ON Transactions(account_id, txn_date);
CREATE INDEX idx_txn_cat ON Transactions(category_id);
CREATE INDEX idx_txn_vendor ON Transactions(vendor);
CREATE INDEX idx_budget_user_month ON Budgets(user_id, month);
CREATE INDEX idx_recurring_due ON RecurringPayments(next_due_date);
CREATE INDEX idx_acc_user ON Accounts(user_id);
CREATE INDEX idx_alert_user ON Alerts(user_id);
CREATE INDEX idx_pred_user ON Predictions(user_id);

